function config = make_default_mcts_config()
    config = struct('update',0, ...
                    'dist',0, ...
                    'select',0, ...
                    'backup',@(nodes,trace) default_backup(nodes, trace), ...
                    'compute_metric', @(obj) metric_probability_max(obj), ...
                    'compute_rollout_metric', @(obj) metric_probability(obj), ...
                    'draw_figures', true, ...
                    'init_samples', 4, ...
                    'initialization', 'pw');
end